function init(self)
	msg.post("#", "hide_Selection")
	self.active = false
end

function on_message(self, message_id, message, sender)
	if message_id == hash("show_Selection") then
	msg.post("#", "enable")
	self.active = true
	elseif message_id == hash("hide_Selection") then
		msg.post("#", "disable")
		self.active = false
	end
end

function on_input(self, action_id, action)
	-- Add input-handling code here
	-- Remove this function if not needed
end