function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("#", "hide_achievements")
	msg.post("#music", "play sound")
	self.active = false
end

function on_message(self, message_id, message, sender)
	if message_id == hash("show_achievements") then
		msg.post("#", "enable")
		self.active = true
	elseif message_id == hash("hide_achievements") then
		msg.post("#", "disable")
		self.active = false
	end
end