function init(self)
	{
		-- it just works
	    -- #thuglife

		-- not 100% done, needs work
		-- require it in selection gui and yada yada yada
		
		table {}
		table[1] = "a"
		table[2] = "ai"
		table[3] = "ar"
		table[4] = "au"
		table[5] = "aw"
		table[6] = "ay"
		table[7] = "b"
		table[8] = "c"
		table[9] = "ch"
		table[10] = "ci"
		table[11] = "ck"
		table[12] = "d"
		table[13] = "dge"
		table[14] = "e"
		table[15] = "e"
		table[16] = "ea"
		table[17] = "ear"
		table[18] = "ed"
		table[19] = "ee"
		table[20] = "ei"
		table[21] = "eigh"
		table[22] = "er"
		table[23] = "eu"
		table[24] = "ew"
		table[25] = "ey"
		table[26] = "f"
		table[27] = "g"
		table[28] = "gn"
		table[29] = "h"
		table[30] = "i"
		table[31] = "ie"
		table[32] = "igh"
		table[33] = "ir"
		table[34] = "j"
		table[35] = "k"
		table[36] = "kn"
		table[37] = "l"
		table[38] = "m"
		table[39] = "ng"
		table[40} = "o"
		table[41] = "oa"
		table[42] = "oe"
		table[43] = "oi"
		table[44] = "oo"
		table[45] = "or"
		table[46] = "ou"
		table[47] = "ough"
		table[48] = "ow"
		table[49] = "oy"
		table[50] = "p"
		table[51] = "ph"
		table[52] = "qu"
		table[53] = "r"
		table[54] = "s"
		table[55] = "sh"
		table[56] = "si"
		table[57] = "t"
		table[58] = "tch"
		table[59] = "th"
		table[60] = "ti"
		table[61] = "u"
		table[62] = "ui"
		table[63] = "ur"
		table[64] = "v"
		table[65] = "w"
		table[66] = "wh"
		table[67] = "wor"
		table[68] = "wr"
		table[69] = "x"
		table[70] = "y"
		table[71] = "z"
		
	
	
	}