i = 0
s = 0

function init(self)
	
end

function update(self, dt)
	-- Add update code here
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	if message_id == hash("Count") then
		if i <= 3 then
			i = i + 1
			msg.post("OtherCars#CollisionTrigger", "Reset")
			return i
		elseif i >= 4 then
			msg.post("EndScreen#EndScreen", "show_EndScreen")
		end
	end

end